### ISSUE TITLE
Small issue in example

### ISSUE THREAD

**Issue by sideninja** [fee1-dead/flow.rs#1]
Example is missing `self` reference on the line https://github.com/fee1-dead/flow.rs/blob/master/flow-examples/README.md?plain=1#L146
Should be:
`log(greeting.concat(",").concat(self.guest.toString()))`

**Comment by fee1-dead** [comment]
Oops, I guess I let that one slip through :p Even after making PRs fixing the exact same issue to the official repository https://github.com/onflow/sdks/pull/3
